version: "3"
services:
  neo4j:
    image: neo4j:3.0
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/neo4j_rb
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - neo4j
